DataAuthWebApp/Models/ErrorViewModel.cs
using System;

namespace DataAuthWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DataAuthWebApp/Controllers/HomeController.cs
using System.Diagnostics;
using System.Linq;
using DataAuthWebApp.Data;
using DataAuthWebApp.DisplayCode;
using Microsoft.AspNetCore.Mvc;
using DataAuthWebApp.Models;
using DataLayer.EfCode;

namespace DataAuthWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index([FromServices]ApplicationDbContext applicationDbContext,
            [FromServices] MultiTenantDbContext extraAuthorizeDbContext)
        {
            var userLister = new ListUsers(applicationDbContext, extraAuthorizeDbContext);

            return View(userLister.ListUserWithRolesAndModules());
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DataAuthWebApp/Controllers/PersonalController.cs
using System.Linq;
using DataLayer.EfClasses.BusinessClasses;
using DataLayer.EfCode;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace DataAuthWebApp.Controllers
{
    public class PersonalController : Controller
    {
        private readonly PersonalDbContext _context;

        public PersonalController(PersonalDbContext context)
        {
            _context = context;
        }

        // GET: Personal
        public ActionResult Index()
        {
            return View(_context.PersonalDatas.FirstOrDefault());
        }


        // GET: Personal/Create
        public ActionResult Create()
        {
            if (_context.PersonalDatas.FirstOrDefault() != null)
                return RedirectToAction(nameof(Edit));

            return View();
        }

        // POST: Personal/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                var entity = new PersonalData {SecretToYou = collection[nameof(PersonalData.SecretToYou)]};
                _context.Add(entity);
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Personal/Edit/5
        public ActionResult Edit()
        {
            var entity = _context.PersonalDatas.FirstOrDefault();
            if (entity == null)
                return RedirectToAction(nameof(Create));

            return View(entity);
        }

        // POST: Personal/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(IFormCollection collection)
        {
            try
            {
                var entity = _context.PersonalDatas.First();
                entity.SecretToYou = collection[nameof(PersonalData.SecretToYou)];
                _context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Personal/Delete/5
        public ActionResult Delete()
        {
            var entity = _context.PersonalDatas.FirstOrDefault();
            if (entity != null)
            {
                _context.Remove(entity);
                _context.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }


    }
}

DataAuthWebApp/Controllers/StockController.cs
using System.Linq;
using DataLayer.EfCode;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DataAuthWebApp.Controllers
{
    public class StockController : Controller
    {
        private readonly MultiTenantDbContext _context;

        public StockController(MultiTenantDbContext context)
        {_context = context;
        }


        // GET: Stock
        public ActionResult Index()
        {
            var stock = _context.CurrentStock.Include(x => x.AtShop).ToList();
            return View(stock);
        }

        //// GET: Stock/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        //// GET: Stock/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: Stock/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add insert logic here

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: Stock/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: Stock/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add update logic here

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: Stock/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: Stock/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

DataAuthWebApp/Controllers/UsersController.cs
using System.Linq;
using DataAuthWebApp.Data;
using DataAuthWebApp.DisplayCode;
using DataLayer.EfCode;
using Microsoft.AspNetCore.Mvc;
using PermissionParts;

namespace DataAuthWebApp.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly ExtraAuthorizeDbContext _extraAuthorizeDbContext;
        private readonly MultiTenantDbContext _multiTenantDbContext;

        public UsersController(ApplicationDbContext applicationDbContext, ExtraAuthorizeDbContext extraAuthorizeDbContext, MultiTenantDbContext multiTenantDbContext)
        {
            _applicationDbContext = applicationDbContext;
            _extraAuthorizeDbContext = extraAuthorizeDbContext;
            _multiTenantDbContext = multiTenantDbContext;
        }

        public IActionResult Index()
        {
            return View(HttpContext.User);
        }

        public IActionResult List()
        {
            var lister = new ListUsers(_applicationDbContext, _multiTenantDbContext);

            return View(lister.ListUserWithRolesAndModules());
        }


        public IActionResult Roles()
        {
            var roles = _extraAuthorizeDbContext.RolesToPermissions.ToList();
            return View(roles);
        }

        public IActionResult Permissions()
        {
            return View(PermissionDisplay.GetPermissionsToDisplay(typeof(Permissions)));
        }
    }
}

DataAuthWebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

DataAuthWebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DataAuthWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<DataAuthWebApp.DisplayCode.UserListDto>
@{
    ViewData["Title"] = "Home Page";
}

<h2>Welcome to Permission Access Control example</h2>

<p>
    This is an example ASP.NET Core web application to show how you can implement per-row data protection.
    This application uses in-memory database to allow you to easily run the application (it seeds the database on startup)
</p>
<h4>
    Please read the article
    <a href="">Handling data authorization ASP.NET Core and Entity Framework Core</a>
    for how this works.
</h4>


<h3>List of users <small>so you can log in</small> </h3>
<p>NOTE: The Email address is also the Password!</p>
<table class="table">
    <tr>
        <th>User Email</th>
        <th>IsDistrictManager?</th>
        <th>Linked shops</th>
    </tr>
    @foreach (var user in @Model)
    {
        <tr>
            <td>@user.Email</td>
            <td>@user.IsDistrictManager</td>
            <td>@user.ShopNames</td>
        </tr>
    }
</table>

DataAuthWebApp/Views/Personal/Create.cshtml
@model DataLayer.EfClasses.BusinessClasses.PersonalData

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>PersonalData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="SecretToYou" class="control-label"></label>
                <input asp-for="SecretToYou" class="form-control" />
                <span asp-validation-for="SecretToYou" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DataAuthWebApp/Views/Personal/Edit.cshtml
@model DataLayer.EfClasses.BusinessClasses.PersonalData

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>PersonalData</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SecretToYou" class="control-label"></label>
                <input asp-for="SecretToYou" class="form-control" />
                <span asp-validation-for="SecretToYou" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DataAuthWebApp/Views/Personal/Index.cshtml
@model DataLayer.EfClasses.BusinessClasses.PersonalData

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<div>
    @if (User.Identity.IsAuthenticated)
    {
        @Html.ActionLink("Create", "Create")
    }
    else
    {
        <h4 class="text-warning">You need to be logged in to access personal data</h4>
        return;
    }
    @if (@Model == null)
    {
        <h4>You haven't created any personal data yet.</h4>
    }
    else
    {
        <h4>PersonalData</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.PersonalDataId)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.PersonalDataId)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.SecretToYou)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.SecretToYou)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.OwnedBy)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.OwnedBy)
            </dd>
        </dl>

        <div>
            @Html.ActionLink("Edit", "Edit") |
            @Html.ActionLink("Delete", "Delete") |
            <a asp-action="Index">Back to Index</a>
        </div>
    }
</div>

DataAuthWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DataAuthWebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">DataAuthWebApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Users
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownAdminItems">
                            <li>@Html.ActionLink("Your claims", "Index", "Users")</li>
                            <li>@Html.ActionLink("List users", "List", "Users")</li>
                            <li>@Html.ActionLink("List roles", "Roles", "Users")</li>
                            <li>@Html.ActionLink("List permissions", "Permissions", "Users")</li>
                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Personal" asp-action="Index">Personal Data</a></li>
                    <li><a asp-area="" asp-controller="Stock" asp-action="Index">Shop Stock</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - DataAuthWebApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

DataAuthWebApp/Views/Stock/Index.cshtml
@model IEnumerable<DataLayer.EfClasses.MultiTenantClasses.StockInfo>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Stock level
            </th>
            <th>
                In Shop
            </th>
            @*<th></th>*@
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumInStock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AtShop.Name)
            </td>
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { id=item.StockInfoId }) |
                @Html.ActionLink("Details", "Details", new { id=item.StockInfoId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.StockInfoId })
            </td>*@
        </tr>
}
    </tbody>
</table>

DataAuthWebApp/Views/Users/Index.cshtml
@model System.Security.Claims.ClaimsPrincipal
@{
    ViewData["Title"] = "User";
}

<p>Current logged in user claims.</p>

@if (Model?.Identity.IsAuthenticated == true)
{
    <h4>User '@User.Identity.Name'</h4>
    <ul>

        @foreach (var claim in @Model.Claims)
        {
            <li>@claim.ToString()</li>
        }
    </ul>
}
else
{
    <h4>No user is logged in.</h4>
}

DataAuthWebApp/Views/Users/List.cshtml
@model List<DataAuthWebApp.DisplayCode.UserListDto>
@{
    ViewData["Title"] = "All users";
}

<h3>List of users</h3>
<table class="table">
    <tr>
        <th>User Email</th>
        <th>Roles</th>
        <th>District Manager?</th>
        <th>Linked to shop(s)</th>
    </tr>
    @foreach (var user in @Model)
    {
    <tr>
        <td>@user.Email</td>
        <td>@user.RoleNames</td>
        <td>@user.IsDistrictManager</td>
        <td>@user.ShopNames</td>
    </tr>
    }
</table>

DataAuthWebApp/Views/Users/Permissions.cshtml
@model IEnumerable<PermissionParts.PermissionDisplay>

@{
    ViewData["Title"] = "Permissions";
}

<h2>Permissions</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GroupName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShortName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Permission)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModuleName)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GroupName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShortName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @item.Permission.ToString()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModuleName)
            </td>
        </tr>
}
    </tbody>
</table>

DataAuthWebApp/Views/Users/Roles.cshtml
@model IEnumerable<DataLayer.EfClasses.AuthClasses.RoleToPermissions>

@{
    ViewData["Title"] = "Roles";
}

<h2>Roles</h2>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RoleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                Permissions
            </th>
            @*<th></th>*@
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RoleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @string.Join(", ", item.PermissionsInRole.Select(x => x.ToString()))
            </td>
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>*@
        </tr>
}
    </tbody>
</table>