TestWebApp/Models/ErrorViewModel.cs
using System;

namespace TestWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestWebApp/Controllers/AIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PermissionParts;
using RolesToPermission;

namespace TestWebApp.Controllers
{
    public class AIController : Controller
    {
        [HasPermission(Permissions.AI)]
        public IActionResult Index()
        {
            return View();
        }
    }
}

TestWebApp/Controllers/ColorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PermissionParts;
using RolesToPermission;

namespace TestWebApp.Controllers
{
    [HasPermission(Permissions.ADM)]
    public class ColorController : Controller
    {
        private static readonly List<string> MyData = new List<string>{ "Red", "Blue", "Green", "Yellow"};

        [HasPermission(Permissions.PR1_READ)]
        public ActionResult Index()
        {
            return View(MyData);
        }

        [HasPermission(Permissions.PR1_CREATE)]
        public ActionResult Create()
        {
            return View();
        }

        [HasPermission(Permissions.PR1_CREATE)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                MyData.Add(collection["Data"]);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HasPermission(Permissions.PR1_DELETE)]
        public ActionResult Delete(int id)
        {
            MyData.RemoveAt(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

TestWebApp/Controllers/ColorRoleController.cs
// Copyright (c) 2018 Jon P Smith, GitHub: JonPSmith, web: http://www.thereformedprogrammer.net/
// Licensed under MIT license. See License.txt in the project root for license information.

using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PermissionParts;
using RolesToPermission;

namespace TestWebApp.Controllers
{
    public class ColorRoleController : Controller
    {
        private static readonly List<string> MyData = new List<string> { "A", "B", "G", "Y" };

        [HasPermission(Permissions.UserRead)]
        public ActionResult Index()
        {
            return View(MyData);
        }

        //[Authorize(Roles = "Manager")]
        [HasPermission(Permissions.UserChange)]
        public ActionResult Create()
        {
            return View();
        }

        //[Authorize(Roles = "Manager")]
        //http://192.168.0.103:5002/ColorRole
        [HasPermission(Permissions.UserChange)]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here
                MyData.Add(collection["Data"]);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        //[Authorize(Roles = "Manager")]
        [HasPermission(Permissions.UserChange)]
        public ActionResult Delete(int id)
        {
            MyData.RemoveAt(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

TestWebApp/Controllers/Feature1Controller.cs
// Copyright (c) 2018 Jon P Smith, GitHub: JonPSmith, web: http://www.thereformedprogrammer.net/
// Licensed under MIT license. See License.txt in the project root for license information.

using Microsoft.AspNetCore.Mvc;
using PermissionParts;
using RolesToPermission;

namespace TestWebApp.Controllers
{
    public class Feature1Controller : Controller
    {
        [HasPermission(Permissions.ADM)]
        public IActionResult Index()
        {
            return
            View();
        }
    }
}

TestWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using DataLayer.EfCode;
using Microsoft.AspNetCore.Mvc;
using TestWebApp.Data;
using TestWebApp.DisplayCode;
using TestWebApp.Models;

namespace TestWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index([FromServices]ApplicationDbContext applicationDbContext,
                                   [FromServices] ExtraAuthorizeDbContext extraAuthorizeDbContext)
        {
            var userLister = new ListUsers(applicationDbContext, extraAuthorizeDbContext);
            var roleLister = new ListRoles(extraAuthorizeDbContext);

            return View(new HomePageDto(userLister.ListUserWithRolesAndModules(), roleLister.ListRolesWithPermissionsExplained().ToList()));
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestWebApp/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using DataLayer.EfCode;
using Microsoft.AspNetCore.Mvc;
using PermissionParts;
using TestWebApp.Data;
using TestWebApp.DisplayCode;

namespace TestWebApp.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;
        private readonly ExtraAuthorizeDbContext _extraAuthorizeDbContext;

        public UsersController(ApplicationDbContext applicationDbContext, ExtraAuthorizeDbContext extraAuthorizeDbContext)
        {
            _applicationDbContext = applicationDbContext;
            _extraAuthorizeDbContext = extraAuthorizeDbContext;
        }

        public IActionResult Index()
        {
            return View(HttpContext.User);
        }

        public IActionResult List()
        {
            var lister = new ListUsers(_applicationDbContext, _extraAuthorizeDbContext);

            return View(lister.ListUserWithRolesAndModules());
        }


        public IActionResult Roles()
        {
            var roles = _extraAuthorizeDbContext.RolesToPermissions.ToList();
            return View(roles);
        }

        public IActionResult Permissions()
        {
            return View(PermissionDisplay.GetPermissionsToDisplay(typeof(Permissions)));
        }
    }
}

TestWebApp/Views/AI/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Bạn đang vào AI!</h1>

<p>Welcome. You can use AI .</p>

TestWebApp/Views/Color/Create.cshtml
@model string

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>HasPermissionAttribute</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Data</label>
                <input name="Data" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestWebApp/Views/Color/Index.cshtml
@model List<string>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Data
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @for (var i = 0; i < Model.Count; i++)
    {
        <tr>
            <td>
                @Model[i]
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = i })
            </td>
        </tr>
    }
    </tbody>
</table>

TestWebApp/Views/ColorRole/Create.cshtml
@model string

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>HasPermissionAttribute</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Data</label>
                <input name="Data" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TestWebApp/Views/ColorRole/Index.cshtml
@model List<string>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Data
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @for (var i = 0; i < Model.Count; i++)
    {
        <tr>
            <td>
                @Model[i]
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = i })
            </td>
        </tr>
    }
    </tbody>
</table>

TestWebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

TestWebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TestWebApp/Views/Home/Index.cshtml
@using StartupCode
@model TestWebApp.DisplayCode.HomePageDto
@{
    ViewData["Title"] = "Home Page";
}

<h2>Welcome to Permission Access Control example</h2>

<p>
    This is an example ASP.NET Core web application to show how you can implement a roles-to-permissions authorization system.
    This application uses in-memory database to allow you to easily run the application (it seeds the database on startup)
</p>
<h4>Please read the article 
    <a href="https://www.thereformedprogrammer.net/a-better-way-to-handle-authorization-in-asp-net-core/">A better way to handle authorization in ASP.NET Core</a>
    for how this works.</h4>

<p>
    <strong>NOTE:</strong> the @Html.ActionLink("ColorController", "Index", "Color")  and the @Html.ActionLink("Feature1Controller", "Index", "Feature1") 
    are protected by Permissions, so try accessing them either of those when not logged in, 
    or logged in as user Staff@g1.com or Manager@g1.com.
</p>


<h3>List of users <small>so you can log in</small> </h3>
<p>NOTE: The Email address is also the Password!</p>
<table class="table">
    <tr>
        <th>User Email</th>
        <th>Roles</th>
        <th>Allowed Modules</th>
    </tr>
    @foreach (var user in @Model.User)
    {
        <tr>
            <td>@user.Email</td>
            <td>@user.RoleNames</td>
            <td>@user.ModuleNames</td>
        </tr>
    }
</table>



<h3>List of roles, with their permission<small>, but remember that the permissions are filtered by what modules the user is allowed to access</small></h3>
<table class="table">
    <tr>
        <th>RoleName</th>
        <th>Has permission</th>
        <th>Permission description</th>
        <th>Optional Module link</th>
    </tr>
    @foreach (var roleData in @Model.Roles)

    {
        for (int i = 0; i < roleData.PermissionsWithDesc.Count; i++ )
        {
            <tr>
                <td>@(i == 0 ? roleData.RoleName : "")</td>
                <td>@roleData.PermissionsWithDesc[i].PermissionName</td>
                <td>@roleData.PermissionsWithDesc[i].Description</td>
                <td>@roleData.PermissionsWithDesc[i].LinkedToModule</td>
            </tr>
        }
    }
</table>

TestWebApp/Views/Users/Index.cshtml
@model System.Security.Claims.ClaimsPrincipal
@{
    ViewData["Title"] = "User";
}

<p>Current logged in user claims.</p>

@if (Model?.Identity.IsAuthenticated == true)
{
    <h4>User '@User.Identity.Name'</h4>
    <ul>

        @foreach (var claim in @Model.Claims)
        {
            <li>@claim.ToString()</li>
        }
    </ul>
}
else
{
    <p>No user is logged in.</p>
}

TestWebApp/Views/Users/List.cshtml
@model List<TestWebApp.DisplayCode.UserListDto>
@{
    ViewData["Title"] = "All users";
}

<h3>List of users</h3>
<table class="table">
    <tr>
        <th>User Email</th>
        <th>Roles</th>
        <th>Allowed Modules</th>
    </tr>
    @foreach (var user in @Model)
    {
    <tr>
        <td>@user.Email</td>
        <td>@user.RoleNames</td>
        <td>@user.ModuleNames</td>
    </tr>
    }
</table>

TestWebApp/Views/Users/Permissions.cshtml
@model IEnumerable<PermissionParts.PermissionDisplay>

@{
    ViewData["Title"] = "Permissions";
}

<h2>Permissions</h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GroupName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShortName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Permission)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModuleName)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GroupName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShortName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @item.Permission.ToString()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ModuleName)
            </td>
        </tr>
}
    </tbody>
</table>

TestWebApp/Views/Users/Roles.cshtml
@model IEnumerable<DataLayer.EfClasses.AuthClasses.RoleToPermissions>

@{
    ViewData["Title"] = "Roles";
}

<h2>Roles</h2>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RoleName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                Permissions
            </th>
            @*<th></th>*@
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RoleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @string.Join(", ", item.PermissionsInRole.Select(x => x.ToString()))
            </td>
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>*@
        </tr>
}
    </tbody>
</table>